import Link from "next/link";
import { cookies } from "next/headers";
import { AlertTriangle, ArrowRight, BriefcaseBusiness, CircleCheck, Clock3, Rocket, ShoppingBag, TrendingUp, Users } from "lucide-react";
import { createClient } from "@/utils/supabase/server";
import { AiUsageCard } from "@/components/admin/ai-usage-card";

export default async function AdminDashboardPage() {
  const supabase = createClient(await cookies());
  const [usersResult, gigsResult, pendingResult, ordersResult, subsResult, boostsResult, disputesResult, recentResult] = await Promise.all([
    supabase.from("profiles").select("*", { count: "exact", head: true }), supabase.from("gigs").select("*", { count: "exact", head: true }), supabase.from("gigs").select("*", { count: "exact", head: true }).eq("status", "pending"), supabase.from("orders").select("*", { count: "exact", head: true }), supabase.from("provider_subscriptions").select("*", { count: "exact", head: true }).eq("status", "active"), supabase.from("gig_boosts").select("*", { count: "exact", head: true }).eq("status", "pending"), supabase.from("orders").select("*", { count: "exact", head: true }).eq("status", "disputed"), supabase.from("orders").select("*, gigs(title), buyer:profiles!buyer_id(name), provider:profiles!provider_id(name)").order("created_at", { ascending: false }).limit(5),
  ]);
  const queueTotal = (pendingResult.count ?? 0) + (boostsResult.count ?? 0) + (disputesResult.count ?? 0);
  return <div className="workspace-page">
    <section className="workspace-welcome admin-welcome"><div><span className="workspace-eyebrow">Marketplace command center</span><h1>Here’s what needs attention.</h1><p>Monitor marketplace health, clear review queues, and keep every transaction moving.</p></div><Link href="/admin/analytics" className="workspace-primary-action"><TrendingUp size={18} /> View performance</Link></section>
    <div className="metric-grid admin-metrics"><div className="metric-card metric-emphasis"><span className="metric-icon"><Users /></span><div><small>Community</small><strong>{usersResult.count ?? 0}</strong><p>Registered members</p></div></div><div className="metric-card"><span className="metric-icon"><BriefcaseBusiness /></span><div><small>Services</small><strong>{gigsResult.count ?? 0}</strong><p>{pendingResult.count ?? 0} awaiting review</p></div></div><div className="metric-card"><span className="metric-icon"><ShoppingBag /></span><div><small>Orders</small><strong>{ordersResult.count ?? 0}</strong><p>Marketplace transactions</p></div></div><div className="metric-card"><span className="metric-icon"><Rocket /></span><div><small>Active plans</small><strong>{subsResult.count ?? 0}</strong><p>Provider subscriptions</p></div></div></div>
    <div className="admin-attention-grid"><Link href="/admin/gigs"><Clock3 /><div><small>Service reviews</small><strong>{pendingResult.count ?? 0}</strong></div><ArrowRight /></Link><Link href="/admin/gigs"><Rocket /><div><small>Boost requests</small><strong>{boostsResult.count ?? 0}</strong></div><ArrowRight /></Link><Link href="/admin/orders" className={(disputesResult.count ?? 0) > 0 ? "is-urgent" : ""}><AlertTriangle /><div><small>Open disputes</small><strong>{disputesResult.count ?? 0}</strong></div><ArrowRight /></Link><div className="queue-health"><CircleCheck /><div><small>Review queue</small><strong>{queueTotal === 0 ? "All clear" : `${queueTotal} actions`}</strong></div></div></div>
    <AiUsageCard />
    <section className="workspace-panel admin-orders-panel"><div className="panel-heading"><div><span>Live activity</span><h2>Recent orders</h2></div><Link href="/admin/orders">View all <ArrowRight size={15} /></Link></div><div className="admin-responsive-table"><table className="data-table"><thead><tr><th>Service</th><th>Buyer</th><th>Provider</th><th>Status</th><th>Created</th></tr></thead><tbody>{recentResult.data?.map((order: any) => <tr key={order.id}><td><strong>{order.gigs?.title ?? "Unknown service"}</strong></td><td>{order.buyer?.name ?? "Unknown"}</td><td>{order.provider?.name ?? "Unknown"}</td><td><span className={`status-badge ${order.status}`}>{order.status.replaceAll("_", " ")}</span></td><td>{new Date(order.created_at).toLocaleDateString()}</td></tr>)}{!recentResult.data?.length && <tr><td colSpan={5}><div className="table-empty">No orders have been placed yet.</div></td></tr>}</tbody></table></div></section>
  </div>;
}
